### PR TITLE
Add condition to generating value

### PR DESCRIPTION
**Pull request by dwojcik96**
The added condition, which provides clearing returning value when the input is empty. When we start to type again - the country code will be added.

### CODE REVIEW

**Comment by catamphetamine** [comment]
Why would you do that?

**Comment by dwojcik96** [comment]
> Why would you do that?

It will be very helpful for persons which are using redux-form and need to validate that value is exist. It does not have an impact on returning proper value with country code.

**Comment by catamphetamine** [comment]
@dwojcik96 
Not understand.
If the value is not filled in then check for `undefined` value.

**Comment by dwojcik96** [comment]
@catamphetamine If you are using redux-form, you have a possibility to implement own validation.
When I want to validate my form's values by that value is exist or not. Actually, return value from PhoneInput, even then our input is empty, has a country code.

**Comment by catamphetamine** [comment]
@dwojcik96 
Not understand.

**Comment by dwojcik96** [comment]
When you clear your input, your PhoneInput component returning value with only country code -> It will be more clear if returning value will be null/undefined. Moreover, my propose still contain a country code, and when you type again, it will be added.

**Comment by catamphetamine** [comment]
I still don't understand what you mean.
But ignore it.

**Comment by dwojcik96** [comment]
You typed some value in input with USA country code -> 123 456 (+1 123 456),
but you would remove whole value. If you do this, your value saved in redux-form should be null/undefined, but looks like: +1.. . You returning value still has a country code. It's is very problematic to validate values from the form. My proposition checking that value is exist, if not then return null, in the other hand (for example when you are start type again) return value has been properly format and will have a country code -- it happens because you still contain country code in a separate variable.

**Comment by catamphetamine** [comment]
> You typed some value in input with USA country code -> 123 456 (+1 123 456),
but you would remove whole value. If you do this, your value saved in redux-form should be null/undefined, but looks like: +1.. .

See the demo: `value` is `undefined` in this case.
Perhaps that's some `redux-form` bug when it's not clearing the value.

**Comment by catamphetamine** [comment]
> you have right. But maybe you consider my proposition? If not, I understand

If it's a bug in `redux-form` then they should fix it, not the other way around.

**Pull request closed without merging**
