### PR TITLE
Update <img> tag for accessibility

### PR DESCRIPTION
**Pull request by jbrower2**
Add `role="presentation"` and `aria-hidden="true"` to flag `` tag for accessibility.

This is to satisfy [Web Content Accessibility Guidelines Success Criterion 1.3.1: Info and Relationships](https://www.w3.org/TR/WCAG21/#info-and-relationships).

### CODE REVIEW

**Comment by catamphetamine** [comment]
@jbrower2 Just `role="presentation"` is sufficient.
https://www.w3.org/TR/2017/WD-wai-aria-practices-1.1-20170628/examples/presentation/PresentationRoleExamples.html
Also, don't change the line ending in the end.

**Comment by catamphetamine** [comment]
@jbrower2 
Don't change the line ending in the end.

**Comment by jbrower2** [comment]
@catamphetamine Sorry about the line ending. I was editing this in the github UI, and it seems that it automatically adds the line ending whenever I commit. Will check this out on my machine.

**Comment by catamphetamine** [comment]
@jbrower2 Ah, whatever, I'm merging.

**Comment by catamphetamine** [comment]
@jbrower2 Published `react-phone-number-input@3.0.21`.
Thx.

**Pull request merged**
