### PR TITLE
Add United States Minor Outlying Islands to flags.js

### PR DESCRIPTION
**Pull request by ebetancourt**
I'm currently getting this issue in production:

screen-shot-2019-03-05-18-27-56

am trying to fix it by looking at this commit: https://github.com/catamphetamine/react-phone-number-input/commit/04078bf5b0c26436e389752340195a3755a41240#diff-48d17c96dc597caf3f7b5e4024466053

I'm not sure how to build and replace on my local to test, but if you let me know the commands, I'd be happy to do so.

### CODE REVIEW

**Comment by catamphetamine** [comment]
Yes, the UM country and several others were removed because it has been discovered that they're not supported by Google's `libphonenumber` library.
https://github.com/googlei18n/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml
Which means they'd get parsed by `libphonenumber` incorrectly.

**Comment by ebetancourt** [comment]
@catamphetamine does this mean they should no longer appear in the dropdown? Because right now, it's available in the dropdown. Should UM be added to `SKIP_COUNTRIES` in this file: https://github.com/catamphetamine/react-phone-number-input/blob/master/source/countries.js#L3 then?
screen-shot-2019-03-07-15-27-34

**Comment by catamphetamine** [comment]
@ebetancourt 
> does this mean they should no longer appear in the dropdown? 

Yes

> Because right now, it's available in the dropdown.

It's not:

image

Perhaps you have an old version of the package installed.

**Comment by catamphetamine** [comment]
Or maybe it’s not an old version and it’s something else then.
I guess it could be a bug.
You can try to debug it to see why the outlying islands aren’t removed in
your case.

**Comment by ebetancourt** [comment]
Thanks, maybe something went wrong in the build process. I'll compare my version to the latest and try an update.

**Comment by catamphetamine** [comment]
You could also restart with a basic example as in the demo.
Then you could re-add stuff until it possibly breaks and then you’d know
which property caused the issue.
For example, try it without the flags property.

**Comment by catamphetamine** [comment]
@ebetancourt 
FYI
I discovered that the `throw new Error("Unknown country")` approach is flawed because if a developer uses a geolocation service that returns, say, "AB" (Abkhazia) for a user's country code and then this country code is passed to the `<PhoneInput/>` component — the component would break and would throw the error.
I fixed that in the latest release `react-phone-number-input@2.3.9`.
Now it doesn't throw when it encounters an unknown country code: it just logs an error to the console and keeps working (it assumes no `country` has been changed in such cases).

**Pull request closed without merging**
