### PR TITLE
Include Kosovo in the list of countries

### PR DESCRIPTION
**Pull request by altinukshini**
The Kosovo svg flag is already there, so this should be an easy fix.
https://github.com/catamphetamine/react-phone-number-input/blob/53363370ce7a389a2e7a46a02747fa6d2f4ddd77/resources/flags/xk.svg

### CODE REVIEW

**Comment by catamphetamine** [comment]
See my comment in the PR: https://github.com/catamphetamine/react-phone-number-input/pull/147

I described a way for adding any new country there.
You can ask questions there too.

**Comment by catamphetamine** [comment]
The `.filter()` line you're referring to has been removed in the latest commit because it didn't change anything.

**Comment by altinukshini** [comment]
That's right, `.filter()` does not change anything now, since you removed the "XK" when you updated the bundle (https://github.com/catamphetamine/react-phone-number-input/commit/7a007752eef9eab50e2d926edad6fd67497d4ca2) and created the default.json (https://github.com/catamphetamine/react-phone-number-input/commit/84e9d68365361dc5cc77b614d26b1dcf9b819234).

And that README file you created (https://github.com/catamphetamine/react-phone-number-input/commit/84e9d68365361dc5cc77b614d26b1dcf9b819234#diff-05d18a9525319a319d77f634ae61ad4b) is nuts man!

This is github in case you happen to have mistaken the platform in which you express your political frustrations! I'm sorry for your views though.

**Comment by catamphetamine** [comment]
If somebody accepts the annexation of Kosovo then it means that USA can come to any country and bomb it into stone age and get away with it.
It has happened to Yugoslavia, it has happened to Iraq, it has happened to Lybia.
Now they want to destroy Syria.
And you live in your little Kosovo and don't give a damn about those innocent people getting killed — you only care for youself.
I'm not that kind of person.
I stand for freedom and true democracy.

> This is github in case you happen to have mistaken the platform in which you express your political frustrations!

I'm not frustrated in any way.
The bombing of Yugoslavia was an unfortunate incident but such things happen throughout the history.
It's important though to not forget about such things so that they don't repeat themselves.

In fact, that's you who expresses his political frustrations here.

> I'm sorry for your views though.

I'd say the same for you.

**Comment by propheth** [comment]
First, I have not a single once of sympathy for NATO. What was done in Iraq, Libya, Syria, Russian sanctions I'm not a supporter.  I have good Serbian friends. I look up to your president of Russia, skillful retaking of Crimea. He is a man standing against oppression. I also believe that Constantinople should not have been taken from the Orthodox Christians and the things that was being done during the time of the Ottomans have not been righteous.

That being said, what happened in Bosnia and Kosova was not right either. I have family that we're saved during that intervention from the evil of the Serbs, there we're good righteous Serbs as well who tried to help the oppressed from their own. The sooner you can come to terms with this the better for both of our worlds. Everything is not black or white. What ever good or bad is done should be acknowledge even if its against yourself, else it is just nationalism or racism. 

Now it has become more than just fighting for piece of land there are other bigger issues at hand. If your world is meant to have it, it will be, if not it wont. This kind of behavior will only cause division among the religious and believer in God. What you should be fighting is not about the Kosova flag but the "rainbow" flag which is spreading like a disease into our libraries and code. It is better that we unite in this and leave the rest to God.

**Comment by altinukshini** [comment]
Sure, thanks for your involvement anyways! There's always an alternative.

Have a look at the ISO standard in the meantime, you might want to implement it, 3166, 3166-1 or even 3166-2 to be more inclusive perhaps, and thus avoid any accusations in the future. https://www.iso.org/obp/ui/#iso:pub:PUB500001:en

Cheers!

**Comment by propheth** [comment]
Not trying to convince you to add the flag. If you don't want to allow anything it is up to you because you are the owner of this project. Flags are a symbol of nationalism anyways, hopefully you disallow the "rainbow" flag anywhere. The code can always be forked if needed for whoever that needs it.

**Comment by catamphetamine** [comment]
@propheth What I can understand is this: Kosovo was Serbian, then Ottoman Empire came and took it from them, and then they took it back, but by the time they took it back it has already been occupied by Albanians for several centuries.
Now it's a difficult question: on one hand, Serbs have the right to reclaim their land, but what should they do with the foreign people who live there?
They can't just destroy them, because it would be inhuman (like Hitler did).
They are not Nazis, so they employ a policy of opressing Albanians slightly so that they move back to Albania.
Would I agree with such "soft" extermination policy?
I guess I would.
You may call it racist, but there's nothing racist here.
It could be Germans instead of Albanians and it could be French instead of Serbs.
I don't favour Serbs over Albanians because they're slavic or something.
I just think logically.
Suppose you're forced out of your own house by a bank, and your house is taken by, say, some Chinese people (might be any nationality).
They live there for 10 years, and then finally the court decides that the bank forcing you to leave your home was illegal and fraudulent, so they give your house back to you.
But now there're those Chinese people living in there.
And it's winter.
You can't just force them out.
So you gradually force them out, being a soft force.
You limit their freedom gradually.
If they fight back you start bringing force into the equation.
If they refuse to leave, if they fight back, you start abusing them, start pushing them so that they leave.
I'd say it's a perfectly valid practice.
It's not "democratic" but democracy is a myth, there's no such thing.

**Comment by propheth** [comment]
Logically, first thing, no one actually owns any land, we are here only for a while. Ownership of land is only an illusion even more so a race owning land.

Usury is prohibited in almost all religions and scripture. The only one wrong here will be he who deals with usury. So you, the bank, the court are guilty.

If the Chinese person buys it free of usury he will be rightfully entitled to the house; softly exterminating them would be a sin on you because you're not righteous in the first place.

If bought on usury then exterminating the children would be a sin because they had nothing to do with the transaction, but you're not righteous in the first place to exterminate anyone.
 
But both your children and their children are innocent and can live together both are given the opportunity to be in the land, build two small houses and live in peace. Whoever exterminates then they have done wrong.

**Comment by catamphetamine** [comment]
> Logically, first thing, no one actually owns any land, we are here only for a while. Ownership of land is only an illusion even more so a race owning land.

It's true that there's no such thing as owning something.
But in today's society there has always been a concept of "property".
For example, you live in your house and it's your "property".
If someone comes with a gun and forces you out of your own house will you try to reclaim it back by force?
You certainly will.
And when  you find out some other people are already living in your house will you be forcing them out?
Or will you gift your house to them?
I don't think anyone would gift their own house to some other people.
Everyone is most likely to fight for it. Fight until the end.

> Usury is prohibited in almost all religions and scripture because of its destructiveness to society. The only one wrong here will be he who deals with usury and brought it upon themselves. So you, the bank, the court are guilty.

No, "you" are not guilty in this case.
Bank is, because it's "usury" and is "prohibited".
But "you" is not guilty in any way.

> If bought on usury then exterminating the children would be a sin because they had nothing to do with the transaction, but you're not righteous in the first place to exterminate anyone.

Yes, they had nothing to do with the transaction, and they are innocent.
But the original owners of the house are innocent too.
If those children force the original owners from the house that would be a sin and that wouldn't be righteous in the same way.

> If the Chinese person buys it free of usury he will be rightfully entitled to the house; 

Well, it's not that simple.
Now you have two parties claiming their legal rights over the same house (property).
And you can't simply say that one of them is right and the other is wrong.
Both of them are innocent.
So not a single one of them can be considered "guilty" or "wrong".
So, in Kosovo it's the same: neither Albanians nor Serbs are "right" in this situation.
Serbs originally owned the house but were forced out of it.
Albanians "bought" the house.
Now the court says that focing Serbs out of their home was illegal.
And Serbs come back to the house.
Now what should be the right decision in this case?
Force Albanians out of the house?
But they are innocent, because they "bought" it.
Force Serbs out of the house?
But they are innocent too, because they are the original owners of the place.
So there's no decision actually.
The only simple decision is for them to fight each other to death and the winner takes the house.
Except that both parties loose from that: they both become weak, and the house is partially destructed.
But there is no other way.
That's the way things are in nature.
Now, what happened in Kosovo is that some powerful stranger — a local gang leader — decided to take part in the fight just for fun.
So the gang leader comes and beats Serbs really bad, and so they run away.
Now, only Albanians are left in the house and the gang leader proclaims them being the "true owners" of the house.
Will you accept such a proclamation of independence?
I certainly won't.
If you will then that gang leader might come to your house and force you out of it, and everybody will accept it again.
If it was just a fight between Serbs and Albanians then I'd agree with the outcome.
But this fight wasn't fair, it was between NATO and Serbs, so I don't agree with the outcome.
You'll have to re-play it if you want it to be fair.
E.g. Kosovo vs Serbia, without USA.
If you win then you get your independence.

> But both your children, their children and of you and them who repent and do good are innocent and can live together both are given the opportunity to be in the land, build two small houses and live in peace. Whoever exterminates then they have done wrong.

That would be the best scenario: just live in piece.
No separation into separate countries: just one country and some autonomy.
And no war.
Except that it didn't work out, as you can see.
And it's just how nature is, that's how people are.

> Try not to see it in terms of race, nationality but a persons actions. As this is how we will be judged, God does not see race, color or nationality; each person by his actions. Also I truthfully really don't know much of the history but it doesn't matter now.

We can't ignore racism because it's always present.
We always prefer people of our own race.
That's our nature, that's biology, that's evolution.
Democracy is bullshit if you ask me.
But we have to wear masks and say "oh, democracy this, democracy that".
In reality we are all bloody animals.

> The form of "democracy" in the world today is a scam to herd the masses and give rule to the oppressors, except in a few countries.

True, there's no democracy in today's world.
Actually, I even think that democracy simply won't work because inside we are all selfish and cruel animals.
Democracy only works as long as you have enough money.

**Comment by catamphetamine** [comment]
@propheth By the way, you seem like a good man : )

**Comment by propheth** [comment]
You too 👍

**Comment by kovachwt** [comment]
@catamphetamine 

I think this whole discussion is bonkers, but let's use your own logic here and come to a couple of conclusions:

Regarding the "Serbs were there first, so it's their territory" argument: Why are you drawing the line at Kosovo, why not remove all countries which are now on previously owned land? If you really believe what you are saying, you would remove most countries on the American continents, Australia etc. Why don't you add some more filtering code and remove them also?

Your other argument, that places should be fought over and whoever wins the war gets to keep the place, is directly opposite that first one.
But even with that logic, didn't Kosovo fought and won in that conflict? They aligned themselves with a stronger ally and won. That's how fights work, they don't exist in a vacuum, parties align themselves and the stronger alliance wins. So with your logic: Kosovo won, the Serbs lost, and you are now arguing against the winner.

Your arguments fall apart when taken to their logical conclusions.  So perhaps you should avoid politics altogether, and not make it intentionally harder for people to work and live their lives...

**Comment by catamphetamine** [comment]
@kovachwt 

> Regarding the "Serbs were there first, so it's their territory" argument: Why are you drawing the line at Kosovo, why not remove all countries which are now on previously owned land?

My point is that the strongest one should take the territory.
It's like a prize in a competition.
E.g. Ottoman Empire was strong so they had the right to take Kosovo.
Then they became weak and so Serbs took Kosovo back by force and they had right to do it.
So, if Serbs are strong that means that they deserved Kosovo as part of their Yugoslavia.
But now Serbs are weak, so Kosovo has been taken from them.
If it was taken by Albanians alone then I would accept it because it would mean that Albanians deserved it.
But it was not taken by Albanians if you see the bigger picture, it was taken by NATO actually.
So my point is that it's unfair, and it's not how natural selection is meant to be.
This is the reason why I don't agree with the annexation of Kosovo.
Serbs had the right to own Kosovo because they took it from Ottoman Empire.
One could say they "bought" it, like in a supermarket.
And then a local gang leader comes to them on a street and threatening them with a gun takes it from them and gives it to Albanians just because he likes it that way.
That's what I find unfair.
And I don't agree that Albanians in Kosovo had right for independence.
Autonomy — yes. Independence — no.

> But even with that logic, didn't Kosovo fought and won in that conflict? They aligned themselves with a stronger ally and won.

That was the "stronger ally" who won.
Otherwise they'd loose completely.

> Your arguments fall apart when taken to their logical conclusions. So perhaps you should avoid politics altogether, and not make it intentionally harder for people to work and live their lives...

No, my arguments are perfectly logical and valid.
Perhaps that's you who should avoid politics and not make it harder.

**Comment by kovachwt** [comment]
But with your same logic NATO won Kosovo, they are the strongest, they bought it, it's theirs now and they get to decide what to do with it. They decided to let the population that lives there make a country. Your own logic of accepting the stronger winner dictates that you accept this...

**Comment by catamphetamine** [comment]
> But with your same logic NATO won Kosovo, they are the strongest, they bought it, it's theirs now and they get to decide what to do with it.

Yes, USA was strong and it won Kosovo so they have the right to do whatever they want with it.

> They decided to let the population that lives there make a country.

Yes, this is how it happened.

But because USA is our enemy we must not accept its decisions.
I don't like what USA does so I don't support its actions.
If Albanians won without the intervention of NATO I'd accept the independence of Kosovo.
But because I don't agree with USA foreign policy I don't agree with the independence of Kosovo made by USA.

**Comment by catamphetamine** [comment]
@kovachwt This is the problem: now your independence is forever tied to the words "USA" and "NATO".
Perhaps eventually you will get recognized internationally, and they everywhere "XK" country code will be added.
But because "XK" is not a valid country code now there's no reason to add Kosovo as a separate country.
Maybe some day America is not that strong anymore and the results of the war will be re-evaluated.
And maybe then Kosovo becomes part of a bigger balkanian territory.
And if they recognize your independence now then they won't have the right to bring you back into their state.
So they deny your independence.
It's for the future.

**Comment by kovachwt** [comment]
Sorry, I'm not from Kosovo. 

I'm from a nearby Slavic country that has historically not been allowed to exist and be independent. 
Thankfully we worked a lot, had some help, and now seem to be making progress on that issue.


> But because USA is our enemy we must not accept its decisions.

Why not do a bit more filtering and also block USA from using the component?

**Comment by catamphetamine** [comment]
> I'm from a nearby Slavic country that has historically not been allowed to exist and be independent.

Well, I don't know anything about that because I was never interested in your countries.
There's too much happening in this world to keep track of everything.

> Thankfully we worked a lot, had some help, and now seem to be making progress on that issue.

Good for you.
I don't care actually whether someone gains independence or not.
I just care about whose decision it is: if it's USA and NATO then I'm against it.
Otherwise it's not my business.

> Why not do a bit more filtering and also block USA from using the component?

You should differentiate between people and politics.
I have no issues with American people.
They're good, just like any other people.
And Albanians are just like any other people.

But politics is not people.
So I don't agree with American politics, but not with the American people.

**Comment by kovachwt** [comment]
But you seem to be directly working against the people of Kosovo, by doing the filtering. 
Politicians are not going to care that someone had to do extra work with some component, but the people that do the work which are definitely not politicians, will care...

**Comment by catamphetamine** [comment]
Well, in real life you have to make decisions.
For example, you see a drowning woman and a drowning child and you only can save one of them.
Which one would you choose?
In any case the other one drown.
So have you killed them?
No.
But you could have saved them?
Yes, you could choose them and save them.
And so they come to you and blame you: "Why did you kill the child?" or "Why did you kill the woman?".
That's how life is: you have to take sides.
And currently I'm on a side which is against USA foreign policy and NATO.
I have to be on that side, because they are our direct enemy.
And so I made my choice.

**Comment by evisar** [comment]
Ti qifsha ata rusinkat qe i ke ke shpija.

**Comment by diteblocknify** [comment]
@catamphetamine Get a girlfriend bro, it will help you relax

**Comment by enishyseni** [comment]
We should be able to somehow report this guy @catamphetamine.  He can't shovel his ideologies forcefully on on other people. This is unacceptable in GitHub discussions!

**Comment by catamphetamine** [comment]
@diteblocknify

> @catamphetamine Get a girlfriend bro, it will help you relax

Ok, so when you're out of constructive arguments you start making this personal and start insulting others.
This is an example of people not being really who they think they are.
I 

@evisar 

> Ti qifsha ata rusinkat qe i ke ke shpija

This is another example of an uncivilized person who just can't behave constructively.

**Comment by catamphetamine** [comment]
@enishyseni
> We should be able to somehow report this guy @catamphetamine. He can't shovel his ideologies forcefully on on other people. This is unacceptable in GitHub discussions!

It's actually you and your friends who "shovel their ideologies forcefully on on other people".
So it's you who should "somehow" be reported.

**Comment by catamphetamine** [comment]
@altinukshini 
I was looking at Google's `libhponenumber` release notes today after a bug report, and saw that XK country has been added to Google's `libhponenumber` metadata in February 2018.
https://github.com/googlei18n/libphonenumber/blob/master/release_notes.txt
If you want XK country be part of this library then the flag for it should be added first to `flag-icon-css` repo here:
https://github.com/lipis/flag-icon-css/tree/master/flags/4x3
I already made an XK flag previously:
https://github.com/catamphetamine/react-phone-number-input/blob/1.x/resources/flags/xk.svg
You can send a pull request with that `4x3` flag to the flags repo, and if it gets merged then tell the author to redeploy it on github pages.
http://flag-icon-css.lip.is/
(he'll probably also want a `1x1` flag icon)
After that XK country could be added to this phone input component.
If you want.

**Comment by catamphetamine** [comment]
@altinukshini 
Since I already have Adobe Illustrator I did a `1x1` flag.
Download it here: https://yadi.sk/d/-sYSa8zj3ZqMCG
You can create a pull request in the flags repo with these two `4x3` and `1x1` flags.

image

**Comment by catamphetamine** [comment]
@altinukshini 
Actually, turns out they already have a pull request for XK flag: https://github.com/lipis/flag-icon-css/pull/256
The discussion is in the issue: https://github.com/lipis/flag-icon-css/issues/26
So I guess it won't be merged there.

**Comment by smajl** [comment]
If "Autonomous Republic of Crimea" will get its own country code one day, let's hope it will be filtered out as well, right.... 🍿

**Comment by catamphetamine** [comment]
@smajl 

> If "Autonomous Republic of Crimea" will get its own country code one day, let's hope it will be filtered out as well, right....

It certainly won't be added because Crimea is part of Russia and is not a separate country.
In any case, Crimea won't be in Google's metadata so it will still be marked as Ukraine while not being part of Ukraine.
Google shows different maps depending on where the user comes from: for Ukraine it shows Crimea as part of Ukraine, and for Russia it shows it as part of Russia.
So, the rule is: one should try to not get involved in territorial disputes.
If someone proclaims independence then don't acknowledge it unless mostly everyone acknowledges it.
That's the reason Crimea is not acknowledged and it won't be acknowledged for a long time I guess.
That's not a problem, this is how things are in the world.
So I don't go and fight Google.
If I was Google I'd do the same thing.

There are a lot of "self-procclaimed" "autonomous territories" in the world. Not only Crimea, for example, but the whole Ukraine is a set of various "self-procclaimed" "autonomous territories": the People's Repulic of Donetsk, the People's Repulic of Lugansk, for example — even Russia hasn't accepted them yet.

In case you're curious take a look at the list of international disputes:
https://en.wikipedia.org/wiki/List_of_territorial_disputes

**Comment by catamphetamine** [comment]
"XK" territory flag has been added to the flags repo:
https://github.com/lipis/flag-icon-css/pull/501
"XK" territory is also supported by Google's `libphonenumber`:
https://github.com/googlei18n/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml
Therefore I added "XK" territory to the list of selectable territories in the phone number input component in `react-phone-number-input@2.3.7`.

**Pull request closed without merging**
