### PR TITLE
allow flags to be a function

### PR DESCRIPTION
**Pull request by danalloway**
allow flags to also be a function that takes a country code and returns the necessary React element

### CODE REVIEW

**Comment by catamphetamine** [comment]
Would you mind describing the scenario requiring this sort of change?

**Comment by danalloway** [comment]
absolutely!

tl;dr
I don't want to manage a list of country codes

Passing in flags as an object of `Code: Element` means I have to manage / process that somewhere and reduce it down into a large object of codes to elements to render them.

Instead, if `react-phone-number-input` can call a function with the code its currently rendering, then I can just return `<CountryFlag countryCode={countryCode} />` and I no longer need to manage a large map of data => elements

**Comment by danalloway** [comment]
`<CountryFlag />` is a component I wrote that detects Emoji support and tries to render the flag as an Emoji first, and if not, falls back to a 4x3 SVG version from a CDN

using it via a function for `flags` in your component will allow my project to have 0 knowledge of emoji's or svgs or country codes... resulting in cleaner code and reduced complexity.

**Comment by catamphetamine** [comment]
I see now.
Yeah, I guess that would be cleaner.
What about introducing a new property instead, called `flagComponent` taking `countryCode` property.
Would it seem cleaner to you?

**Comment by danalloway** [comment]
yes, that would work quite well!

**Comment by catamphetamine** [comment]
Ok, I'll implement that then.

**Comment by catamphetamine** [comment]
Try `react-phone-number-input@0.12.4`.

**Pull request closed without merging**
