### PR TITLE
Update to reflect changes on libphonenumber-js

### PR DESCRIPTION
**Pull request by bryanmytko**
In version 1.0.18 [libphonenumber-js](https://github.com/catamphetamine/libphonenumber-js) replaced the key `country_phone_code_to_countries` with `country_calling_codes` in `metadata.json`. This updates the metadata references in `Input.js`.

### CODE REVIEW

**Comment by catamphetamine** [comment]
Hello brian.
Thanks for taking time to offer a fix for this issue.
I didn't test it at all today when I released the version update for `libphonenumber-js` dependency.
Perhaps I wasn't thinking too straight.
Released the new version `react-phone-number-input@0.15.4` which seems to be working.

**Comment by catamphetamine** [comment]
The funny thing is, when I released the new `libphonenumber-js` I though: "Nah, who even used `country_phone_code_to_countries`, nobody should have used it at all".

**Comment by catamphetamine** [comment]
Screw that, I've just thought that I should have bumped the major version as well.
Released `react-phone-number-input@0.16.0`.
Unpublished `react-phone-number-input@0.15.4` and `react-phone-number-input@0.15.3`.

**Comment by bryanmytko** [comment]
@catamphetamine Awesome, seems to work for my project! Thanks for the quick reply!

**Pull request closed without merging**
