### PR TITLE
Fix Vietnamese translations

### PR DESCRIPTION
**Pull request by hoantran-it**
Some minor fix. Thanks!

### CODE REVIEW

**Comment by catamphetamine** [comment]
Previously you already submitted Vietnamese translation:
https://github.com/catamphetamine/react-phone-number-input/pull/206/
So there already is one, and you're adding yet another one here.

**Comment by hoantran-it** [comment]
@catamphetamine Yes, it's a mistake and I don't know how to remove the old one 😞

**Comment by catamphetamine** [comment]
Can I just rename `vn.json` to `vi.json` and close this pr?

**Comment by hoantran-it** [comment]
Yes, if having any change I will create another carefully. Thanks!

**Comment by catamphetamine** [comment]
Released `react-phone-number-input@2.2.18`

**Pull request closed without merging**
