### PR TITLE
Fixing issue for iOS Autofill.

### PR DESCRIPTION
**Pull request by davityavryan**
Hey there is a minor bug.

iOS AutoFill does not add + sign when prefilling input (it shows that it will fill +49 172 5555555 number but prefills input with +49491725555555) and if Country is already selected (for example Germany, +49) final value becames +4949172 5555555. which is vaid BTW for [https://github.com/albeebe/phoneformat.js/](url) 😀

So I think having extra check with be great.

BTW: Steps to reproduce issue

1. set country (Germany as an example)
2. and paste 491725555555 in input field.

input value will become `+49 491 725555555` which is not right.

### CODE REVIEW

**Comment by catamphetamine** [comment]
> iOS AutoFill does not add + sign when prefilling input 

Checked on my iPhone and it prefills correctly

**Comment by catamphetamine** [comment]
> (it shows that it will fill +49 172 5555555 number but prefills input with 491725555555)

If it shows something then it must prefill that exact value which it does

**Comment by davityavryan** [comment]
I agree with 

> If it shows something then it must prefill that exact value which it does

My bad I have did mistake in comment. it should be

> (it shows that it will fill +49 172 5555555 number but prefills input with +49491725555555)

**Comment by catamphetamine** [comment]
> (it shows that it will fill +49 172 5555555 number but prefills input with +49491725555555)

it prefills correctly for me on iPhone with Russia selected.
perhaps an iOS bug.
I'm on iOS 11.
See the screenshots.

img-0499

img-0500

**Comment by davityavryan** [comment]
try with "Default country" one :)

**Comment by catamphetamine** [comment]
> try with "Default country" one

Still works

**Comment by davityavryan** [comment]
img_2f4f680ee6dc-1

**Comment by davityavryan** [comment]
iOS 11.0.2

**Comment by catamphetamine** [comment]
Well, what can I say.
It works for me on the same iOS version as it doesn't work for you.
It can be something with your stored number or something else.

**Comment by davityavryan** [comment]
can you please apply same number? just store it like "+491725555555" in your contact and then pick it up.

**Comment by catamphetamine** [comment]
It won't let me insert a number from the contacts list

**Comment by davityavryan** [comment]
Click on "Autofill contact" -> "Other Contact..." -> find contact and select number.
Thanks in advance.

**Comment by catamphetamine** [comment]
I don't have any "Autofill contact"

**Comment by davityavryan** [comment]
interesting... :/
img_47d393e769b1-1

**Comment by catamphetamine** [comment]
It only let me autofill german number if I mark it as my own.
It autofills correctly in this case.

**Comment by davityavryan** [comment]
:) I am so sorry but it is not.

img_66b7bfb24790-1

is Autofill enabled in your iOS? it is in Settings->Safari->Autofill

**Comment by catamphetamine** [comment]
Yes it is enabled in settings and is working as expected for me

**Comment by davityavryan** [comment]
ok then. what can I say? :)

it is not working for my 2 iPhones.

if you think it is obsolete you can close this pull request. Or maybe you can try with some other iPhone. :/

p.s. I am using "Germany" as a region on both iPhones(iPhone 7 and 6s). maybe it's related to that, I mean formating.

**Comment by catamphetamine** [comment]
Ok, I'm closing this PR then

**Pull request closed without merging**
