### PR TITLE
Adds French locale

### PR DESCRIPTION
**Pull request by Romusc**
Adds French locale for country names

### CODE REVIEW

**Comment by Romusc** [comment]
Yes it is "ext." !

**Comment by catamphetamine** [comment]
Ok, you can re-create this PR with only 1 file changed then and I'll merge it.

**Comment by Romusc** [comment]
There you go, and thanks for the lib it's great !

**Comment by catamphetamine** [comment]
Thanks, released `react-phone-number-input@1.1.7`

**Pull request merged**
